// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKIuJfRvyQNgZjsQChBqZTQkhqiF8gLys',
    appId: '1:1068315374313:web:8b69506c8e6e86d768f678',
    messagingSenderId: '1068315374313',
    projectId: 'crud-746d2',
    authDomain: 'crud-746d2.firebaseapp.com',
    storageBucket: 'crud-746d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByMZ2Z1d5keL_In9M3ehhDRd0BYNAy3MY',
    appId: '1:1068315374313:android:e2d681e1c458a22768f678',
    messagingSenderId: '1068315374313',
    projectId: 'crud-746d2',
    storageBucket: 'crud-746d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEfGCWo7hz-RfXrUKrfL8udjMAUz_c9OA',
    appId: '1:1068315374313:ios:0e99094603660ad668f678',
    messagingSenderId: '1068315374313',
    projectId: 'crud-746d2',
    storageBucket: 'crud-746d2.appspot.com',
    iosBundleId: 'com.example.flutterCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEfGCWo7hz-RfXrUKrfL8udjMAUz_c9OA',
    appId: '1:1068315374313:ios:0e99094603660ad668f678',
    messagingSenderId: '1068315374313',
    projectId: 'crud-746d2',
    storageBucket: 'crud-746d2.appspot.com',
    iosBundleId: 'com.example.flutterCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKIuJfRvyQNgZjsQChBqZTQkhqiF8gLys',
    appId: '1:1068315374313:web:bb183f6b8eaff9f968f678',
    messagingSenderId: '1068315374313',
    projectId: 'crud-746d2',
    authDomain: 'crud-746d2.firebaseapp.com',
    storageBucket: 'crud-746d2.appspot.com',
  );
}
